###
retrieve all activities

GET http://localhost:8000/api/activity

###
retrieve all the activities for a given level 

GET http://localhost:8000/api/activity/1

###
retrieve activities filtered by name 

GET http://localhost:8000/api/activity/3?filter=STEM&lang=sp-ES

###
retrieve activities filtered by  category

GET http://localhost:8000/api/activity/3?filter=music&lang=en

###
retrieve activities filtered by  other

GET http://localhost:8000/api/activity/3?filter=girls

GET http://localhost:8000/api/activity/3?filter=Activities%20only%20for%20boys



###
OPTION for using CORS 
OPTION http://localhost:8000/api/activity/3?filter=music&lang=en

###


PUT http://localhost:8000/api/enroll/
Content-Type: application/json

{
  "student_id": "1",
  "activity_id": "es"
}

